# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\"\x07\n\x05\x45mpty\" \n\rModelResponse\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\"\x1e\n\x0bModelUpdate\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2W\n\x0f\x46\x65\x64\x65ratedServer\x12\"\n\x08GetModel\x12\x06.Empty\x1a\x0e.ModelResponse\x12 \n\nSendUpdate\x12\x0c.ModelUpdate\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=19
  _globals['_EMPTY']._serialized_end=26
  _globals['_MODELRESPONSE']._serialized_start=28
  _globals['_MODELRESPONSE']._serialized_end=60
  _globals['_MODELUPDATE']._serialized_start=62
  _globals['_MODELUPDATE']._serialized_end=92
  _globals['_ACK']._serialized_start=94
  _globals['_ACK']._serialized_end=116
  _globals['_FEDERATEDSERVER']._serialized_start=118
  _globals['_FEDERATEDSERVER']._serialized_end=205
# @@protoc_insertion_point(module_scope)
